### ISSUE TITLE
请问在windows系统编译nms的时候出现了错误应该怎么办

### ISSUE THREAD

**Issue by Shank2358** [pprp/SimpleCVReproduction#11]
请问在windows系统编译nms的时候出现了错误应该怎么办

**Comment by pprp** [comment]
也不说报错是什么，怎么让人帮你解决呢？

**Comment by pprp** [comment]
https://blog.csdn.net/yangdashi888/article/details/103178870
你先看看这个方案可不可以。因为这个centernet项目我是在ubuntu下跑的，ubuntu下很顺利。

**Comment by Shank2358** [comment]
> https://blog.csdn.net/yangdashi888/article/details/103178870
> 你先看看这个方案可不可以。因为这个centernet项目我是在ubuntu下跑的，ubuntu下很顺利。

谢谢。实在抱歉昨天问题的截图忘了传了，错误提示是error: Unable to find vcvarsall.bat ，问题在编译器-Wno-cpp那里，已经解决，谢谢。另外我想请问一下这个错误是不是和pytorch版本有关系， 用的1.1.0是可以的，但是高版本会有越界错误。谢谢。 File "E:\CenterNet\datasets\pascal.py", line 168, in __getitem__
    w_h_[k] = 1. * w, 1. * h
IndexError: index 101 is out of bounds for axis 0 with size 101

**Comment by pprp** [comment]
这个可能是你数据集的问题，最好通过debug解决
