### ISSUE TITLE
用单类训练的时候map eval为0 ，loss 下不去时为什么

### ISSUE THREAD

**Issue by Jiachenyin1** [pprp/SimpleCVReproduction#12]

**Comment by pprp** [comment]
你指的是centernet吗？
如果是centernet的话，建议检查一下数据标注。这里提供一个标准格式的数据集供参考：
链接：https://pan.baidu.com/s/1unK-QZKDDaGwCrHrOFCXEA 
提取码：pdcv

**Comment by ZxSnow** [comment]
您好，我使用了您提供的racoon的数据集，训练时ap始终为0，请问是怎么回事呢？
