### ISSUE TITLE
bug 发现

### ISSUE THREAD

**Issue by cmsfw-github** [pprp/SimpleCVReproduction#13]
utils的这个函数，shape定义错了，应当是 h,w = heatmap.shape
原来的是w,h
def draw_umich_gaussian(heatmap, center, radius, k=1):
    diameter = 2 * radius + 1
    gaussian = gaussian2D((diameter, diameter), sigma=diameter / 6)
    # print(gaussian.shape)
    # 一个圆对应内切正方形的高斯分布

    x, y = int(center[0]), int(center[1])

    height, width = heatmap.shape

    left, right = min(x, radius), min(width - x, radius + 1)
    top, bottom = min(y, radius), min(height - y, radius + 1)

    masked_heatmap = heatmap[y - top:y + bottom, x - left:x + right]
    masked_gaussian = gaussian[radius - top:radius +
                               bottom, radius - left:radius + right]

    if min(masked_gaussian.shape) > 0 and min(masked_heatmap.shape) > 0:  # TODO debug
        np.maximum(masked_heatmap, masked_gaussian * k, out=masked_heatmap)
        # 将高斯分布覆盖到heatmap上，取最大，而不是叠加
    return heatmap

**Comment by pprp** [comment]
这里没错啊，并不是w,h

https://github.com/pprp/SimpleCVReproduction/blob/575c1eca4d985e973ed98ec98b4ba5aa0aa69255/CenterNet/utils/image.py#L141

**Comment by cmsfw-github** [comment]
> 这里没错啊，并不是w,h
> 
> https://github.com/pprp/SimpleCVReproduction/blob/575c1eca4d985e973ed98ec98b4ba5aa0aa69255/CenterNet/utils/image.py#L141

![Snipaste_2020-11-30_23-15-13](https://user-images.githubusercontent.com/24754360/100627510-0f36e700-3362-11eb-884b-b6e2a2338f02.jpg)
是这个地方出错了，
SimpleCVReproduction/simple_keypoint/heatmap/utils.py /

**Comment by pprp** [comment]
@cmsfw-github fixed Thank you! :smiling_face_with_three_hearts:
