### ISSUE TITLE
注意力机制下面的AFF已经更新了pytorch代码

### ISSUE THREAD

**Issue by 1187697147** [pprp/SimpleCVReproduction#14]
您好，AFF、iAFF的代码已经更新了pytorch版本，希望更新一下！
[https://github.com/YimianDai/open-aff/blob/master/aff_pytorch/aff_net/fusion.py](url)

**Comment by pprp** [comment]
好的，感谢建议！

**Comment by pprp** [comment]
commit 098daa2b2fdf2f9d0fbad8828ae19c9877232c0c
