### ISSUE TITLE
请问在simple_keypoint这个部分中，regression里的test.py运行报错是什么问题？

### ISSUE THREAD

**Issue by ldy958718956** [pprp/SimpleCVReproduction#16]
在simple_keypoint这个部分中，regression里的test.py的65行， “NameError: name 'SIZE' is not defined”， 这里的size指的是图片的size吗？

**Comment by pprp** [comment]
@ldy958718956  SIZE是图片的长和宽，和train.py中IMG_SIZE相同

**Comment by ldy958718956** [comment]
好的，明白&nbsp; 感谢大佬指点



---原始邮件---
发件人: "PJDong"<notifications@github.com&gt;
发送时间: 2020年12月20日(周日) 晚上9:08
收件人: "pprp/SimpleCVReproduction"<SimpleCVReproduction@noreply.github.com&gt;;
抄送: "ldy958718956"<958718956@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [pprp/SimpleCVReproduction] 请问在simple_keypoint这个部分中，regression里的test.py运行报错是什么问题？ (#16)




 
@ldy958718956  SIZE是图片的长和宽，和train.py中IMG_SIZE相同
