### ISSUE TITLE
MOT数据集格式应该是(左上角坐标及长宽)，但是def xyxy2xywh(x): 将其转换为(中心点坐标及长宽)，是不是错了。

### ISSUE THREAD

**Issue by MasonZong** [pprp/SimpleCVReproduction#17]

**Comment by MasonZong** [comment]
MOT数据集格式应该是(左上角坐标及长宽)，但是def xyxy2xywh(x): 将其转换为(中心点坐标及长宽)，是不是错了。
`def xyxy2xywh(x):
    # Convert bounding box format from [x1, y1, x2, y2] to [x, y, w, h]
    # y = torch.zeros_like(x) if isinstance(x,
    #                                       torch.Tensor) else np.zeros_like(x)
    y = [0, 0, 0, 0]

    y[0] = (x[0] + x[2]) / 2
    y[1] = (x[1] + x[3]) / 2
    y[2] = x[2] - x[0]
    y[3] = x[3] - x[1]
    return y`

**Comment by pprp** [comment]
谢谢指出问题，已修改
