### ISSUE TITLE
Sematic Embbed Block(SEB)

### ISSUE THREAD

**Issue by lab-gpu** [pprp/SimpleCVReproduction#18]
作者你好，我看你的知乎博文，里面提到了SEB模块，关于这个模块，这个github的代码好像并没有添加，请问作者是在哪里看到的这个SEB模块呢?

**Comment by lab-gpu** [comment]
或者有相关的论文吗，搜了一下，没找到，所以问问作者，请问你是在哪里看到的呢

**Comment by pprp** [comment]
也是知乎里一篇文章，对yolov3进行试验和改进。时间太久了，找不到原文了。。

**Comment by lab-gpu** [comment]
> 也是知乎里一篇文章，对yolov3进行试验和改进。时间太久了，找不到原文了。。

好的，我再找找看
