### ISSUE TITLE
camvid data structure

### ISSUE THREAD

**Issue by soans1994** [pprp/SimpleCVReproduction#20]
dear author,

can you please tell me the dataset structure of camvid dataset.

i split images into train val and test. where should be the labels/ground truth image?

**Comment by pprp** [comment]
You can refer to this blog [link](https://blog.csdn.net/qq_41185868/article/details/100146896). 

I recommand you to use a tookit [mmsegmentation](https://github.com/open-mmlab/mmsegmentation)
