### ISSUE TITLE
gpu utilization

### ISSUE THREAD

**Issue by soans1994** [pprp/SimpleCVReproduction#21]
hello author,

i am using your pytorch segmentation implementation. the gpu is not being used. the system is using only cpu. i have cuda device in pytorch. also, why is batch size 1 in your config and what n_workers should i use?

thank you

**Comment by pprp** [comment]
you should run `python -c "import torch; print( torch.is_cuda_available())"` to make sure whether pytorch is properly installed. 

one more thing, this repository pytorch-semseg is borrowed from [here](https://github.com/meetps/pytorch-semseg). pls check the issues [here](https://github.com/meetps/pytorch-semseg/issues)
