### ISSUE TITLE
keypoint heatmap中结果出现-1

### ISSUE THREAD

**Issue by Passion0930** [pprp/SimpleCVReproduction#22]
我输出了神经网络预测的点 结果显示很多图片的输出结果为（-1，-1）这是为什么？

**Comment by pprp** [comment]
具体哪个文件输出了-1发自我的华为平板-------- 原始邮件 --------发件人： Passion0930 ***@***.***>日期： 2021年8月30日周一 上午10:40收件人： pprp/SimpleCVReproduction ***@***.***>抄送： Subscribed ***@***.***>主    题： [pprp/SimpleCVReproduction] keypoint heatmap中结果出现-1 (#22)

我输出了神经网络预测的点 结果显示很多图片的输出结果为（-1，-1）这是为什么？
