### ISSUE TITLE
mot evaluate

### ISSUE THREAD

**Issue by ren1202** [pprp/SimpleCVReproduction#23]
能不能直接用cvat或者darklabel标注视频输出gt，再与deep sort输出的result进行比较输出mota、ids这些指标

**Comment by pprp** [comment]
cvat和darklabel可以输出标注，但是格式需要调整。

**Comment by ren1202** [comment]
<frame>, <id>, <bb_left>, <bb_top>, <bb_width>, <bb_height>, <conf>, <x>, <y>, <z> ，是这样的格式吗，但是conf这个好像没法通过标注生成

**Comment by ren1202** [comment]
我用cvat输出了几个指标，格式是否正确，最后的1.0是conf吗，通过标注是不是没法获得conf，所以都是1.0
![image](https://user-images.githubusercontent.com/60747672/131818017-604b8a01-0ebd-4749-a031-a0dedfbdc14e.png)

**Comment by pprp** [comment]
对照这里 https://github.com/pprp/SimpleCVReproduction/blob/9939f8340c54dbd69b0017cecad875dccf428f26/DarkLabel/MOT/DarkLabel_to_MOT_gt.py#L5

**Comment by pprp** [comment]
是的，自己标注只能设置默认为1

**Comment by ren1202** [comment]
这个数值对最终的指标有什么影响吗，比如mota这些指标

**Comment by pprp** [comment]
这个我还没研究过，你可以看看测评的源码

**Comment by ren1202** [comment]
恩，谢谢你的回答
