### ISSUE TITLE
Multi-object in Infrared small target detection

### ISSUE THREAD

**Issue by fwzdev1** [pprp/SimpleCVReproduction#24]
哈喽，

请问作者有没有试过heatmap方法检测多个红外目标中心点？ 
如果有试过的话效果如何？
还有就是，如果我想尝试这个任务的话，只需要修改dataloader应该就可以了吧？
@pprp 

多谢！

**Comment by pprp** [comment]
可以参照centernet进行修改，这个项目当然也可以魔改成支持多个目标的。

**Comment by fwzdev1** [comment]
> 可以参照centernet进行修改，这个项目当然也可以魔改成支持多个目标的。

修改了，效果还可以。但是问提来了，这个十几层的网络inference时间居然花了我15ms的cpu推理时间，相比之下yolov5nano才10ms左右。。。
您知道该咋去修改吗，是不是现有代码（特指detect.py）里面的推理只是最基础的实现，还需要一些trick才能加速？

**Comment by pprp** [comment]
将模型backbone替换为yolov5nano的backbone，或者干脆把这个几层的卷积网络中所有cnn替换为深度可分离卷积，就可以提高cpu上推理速度。

**Comment by pprp** [comment]
@fwzdev1 也欢迎PR多目标实现 😄

**Comment by fwzdev1** [comment]
okok忘记depthwise这点了。等我闲来改改试试！多谢！
