### ISSUE TITLE
The way to config VOCdevkit and the function of annotations_cache

### ISSUE THREAD

**Issue by mastergao57** [pprp/SimpleCVReproduction#26]
作者你好，我想请问一下训练和验证自己的数据集的话，VOCdevkit这个文件夹里该怎么配置。Pascal数据集代码里的annotations_cache又是什么文件？
`cachedir = os.path.join(self.devkit_path, 'annotations_cache')`

**Comment by pprp** [comment]
annotations_cache文件一般是程序自动生成的一个以pkl结尾的临时文件, 详见[link](https://blog.csdn.net/qq_44507953/article/details/105234801) 

训练自己的数据集，可以参考教程 [link](https://www.cnblogs.com/pprp/p/10863496.html)

**Comment by mastergao57** [comment]
我明白了，非常感谢
