### ISSUE TITLE
请问可以补充 BAM模块到即插即用模块里么？

### ISSUE THREAD

**Issue by zhongqiu1245** [pprp/SimpleCVReproduction#7]
请问可以补充BorderDet中的提到的BAM模块到即插即用模块里么？它可以更好的精确定位box，并且付出的时间代价小
paper：BorderDet: Border Feature for Dense Object Detection
https://zhuanlan.zhihu.com/p/163044323

**Comment by pprp** [comment]
收到，近期会补充进来，感谢贡献

**Comment by zhongqiu1245** [comment]
谢谢您的答复和工作！
