### ISSUE TITLE
请问可以补充FPT模块么？

### ISSUE THREAD

**Issue by zhongqiu1245** [pprp/SimpleCVReproduction#8]
将Transformer应用在了FPN上，能涨点
https://github.com/ZHANGDONG-NJUST/FPT
https://arxiv.org/abs/2007.09451

**Comment by pprp** [comment]
好的，感谢留言，我研究一下，最近几天会加上的。

**Comment by zhongqiu1245** [comment]
非常感谢！这个FPT在COCO test-dev上，用于框检测的百分比增益为8.5%，用于遮罩实力检测的mask AP增益6.0%，真的涨点效果惊奇

**Comment by pprp** [comment]
@zhongqiu1245 已添加上去，确实是一个很好的想法。欢迎补充新的模块。
