### ISSUE TITLE
作者可以给出一个简单的案例说明这些模块如何插入VGG或者ResNet50吗？这对于初学者来说是相当友好的。

### ISSUE THREAD

**Issue by cuge1995** [pprp/SimpleCVReproduction#9]

**Comment by pprp** [comment]
@cuge1995 感谢你的提问，plug and play module当初总结是为了改进yolov3模型，给其中加入注意力机制来进行改进。

对应的博客是：https://blog.csdn.net/DD_PP_JJ/article/details/104109369，同样的内容也可以在我的知乎和GiantPandaCV公众号中访问。

除了FPT等作用于FPN的模型，大部分的即插即用模块都是很简单的，在模型的__init__函数中构建，在forward函数中调用即可，非常方便。

当时的实验代码也公开在：https://github.com/GiantPandaCV/yolov3-point 

当时实现了SE, SPP, RFB, ASPP, CBAM, SK等即插即用模块在YOLObackbone中的插入。
